[theme]
primaryColor="#6A0DAD"  # Un morado oscuro
backgroundColor="#1E1E1E"  # Un gris muy oscuro
secondaryBackgroundColor="#2E2E2E"  # Un gris oscuro
textColor="#FFFFFF"  # Blanco para el texto
font="sans serif"